version: "3.8"

services:
    db:
        image: mysql:5.7
        container_name: mysql_container
        environment:
            MYSQL_DATABASE: mysql
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo"
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/entrypoint:/docker-entrypoint-initdb.d
        ports:
            - ${DOCKER_DB_PORT:-33306}:3306
